{
 "title": "Python Measurement",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Ping in ms",
   "type": "stat",
   "description": "Ping to target in ms",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Ping{}" }
   ]
  },
  {
   "title": "RAM in %",
   "type": "gauge",
   "description": "Usage in Percent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "RAM{}" }
   ]
  },
  {
   "title": "Iperf in MB",
   "type": "timeseries",
   "description": "Bandwidth between target and instance via router in MB",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "Iperf" }
   ]
  }
 ]
}